global_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 2.0
  publish_frequency: 0.4
  static_map: true
  resolution: 0.05
  transform_tolerance: 0.5
  inflation_radius: 1.0
  cost_scaling_factor: 7.0
