local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 15.0
  publish_frequency: 1
  static_map: false
  rolling_window: true
  max_obstacle_width: 3.0
  max_obstacle_height: 3.0
  width: 3
  height: 3
  resolution: 0.02
  transfrom_tolerance: 0.5
  inflation_radius: 0.6
  cost_scaling_factor: 1.0
