controller_frequency: 15.0
#The rate in Hz at which to run the control loop and send velocity commands to the base. (double, default: 20.0) 

planner_patience: 5.0
#How long the planner will wait in seconds in an attempt to find a valid plan before space-clearing operations are performed. 
#(double, default: 5.0) 

controller_patience: 15.0
#How long the controller will wait in seconds without receiving a valid control before space-clearing operations are performed. 
#(double, default: 15.0) 

conservative_reset_dist: 3.0
#The distance away from the robot in meters beyond which obstacles will be cleared from the costmap when attempting to clear space in the map. 
#Note, this parameter is only used when the default recovery behaviors are used for move_base.(double, default: 3.0) 

recovery_behavior_enabled: true
#Whether or not to enable the move_base recovery behaviors to attempt to clear out space. (bool, default: true)

clearing_rotation_allowed: true
#Determines whether or not the robot will attempt an in-place rotation when attempting to clear out space. 
#Note: This parameter is only used when the default recovery behaviors are in use, 
#meaning the user has not set the recovery_behaviors parameter to anything custom. (bool, default: true) 

shutdown_costmaps: false
#Determines whether or not to shutdown the costmaps of the node when move_base is in an inactive state (bool, default: false) 

oscillation_timeout: 0.0
#How long in seconds to allow for oscillation before executing recovery behaviors. 
#A value of 0.0 corresponds to an infinite timeout. New in navigation 1.3.1 (double, default: 0.0)

planner_frequency: 0.0 
#The rate in Hz at which to run the global planning loop. If the frequency is set to 0.0, 
#the global planner will only run when a new goal is received or the local planner reports that its path is blocked. 
#New in navigation 1.6.0 (double, default: 0.0)

max_planning_retries: -1
#How many times to allow for planning retries before executing recovery behaviors. 
#A value of -1.0 corresponds to an infinite retries. (int32_t, default: -1) 
