axis_linear_x: 1
axis_linear_y: 0
axis_angular_z: 2
scale_angular_z: 0.6
scale_linear_x: 0.6
scale_linear_y: 0.6

deadman_button: 5   #button on the controller wich has to be pushed while driving
timeOut: 0.1        #timeout to stop robot if no command is recived for X seconds and 
                    #deadman_button is not pushed
